spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: user
    password: admin!
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
